global:
  ecfs_path: "ec:/smoz/harmonie"
  data_path: "/scratch/user/monitor_data"
  webgraf_path: "/scratch/user/CERRA_TU_MONITOR"
  wrk: "/scratch/user/CERRA_TU_MONITOR_WRK"
  monitor_path: "/hpcperm/snh/CERRA_TU/git/Monitor"
  clean_old_exp: false
  maxruns: 2
  dry_run: false
  untar: true

experiments:

  cerra_nrt_eda:
    project: "cerra_tu_eda"
    mbr: 0

  cerra_nrt:
    display_exp: cerra_tu
    project: "cerra_tu"

